J3ko/Moviebase/MVC/Models/Detail/EpisodeDetailEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using J3ko.Moviebase.BOL;

namespace J3ko.Moviebase.MVC.Models.Detail
{
    public class EpisodeDetailEditModel
    {
        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }

        public IEnumerable<InstanceBO> Instances { get; set; }

        [Display(Name = "Instance")]
        public int InstanceId { get; set; }
    }
}

J3ko/Moviebase/MVC/Models/Detail/EpisodeDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace J3ko.Moviebase.MVC.Models.Detail
{
    public class EpisodeDetailModel
    {
        public string Name { get; set; }

        public string Instance { get; set; }
    }
}

J3ko/Moviebase/MVC/Models/Detail/GroupDetailEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using J3ko.Moviebase.BOL;

namespace J3ko.Moviebase.MVC.Models.Detail
{
    public class GroupDetailEditModel
    {
        [HiddenInput(DisplayValue = false)]
        public int GroupId { get; set; }

        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(AllowEmptyStrings = false)]
        public string Description { get; set; }

        public IEnumerable<MediaBO> Media { get; set; }

        [Display(Name = "Media")]
        public int MediaId { get; set; }

        public IEnumerable<SlotBO> Slots { get; set; }

        [Display(Name = "Slot")]
        public int SlotId { get; set; }

        public IEnumerable<ContainerBO> Containers { get; set; }

        [Display(Name = "Container")]
        public int ContainerId { get; set; }

        private List<EpisodeDetailEditModel> _episodes;

        public List<EpisodeDetailEditModel> Episodes
        {
            get
            {
                if (_episodes == null)
                    _episodes = new List<EpisodeDetailEditModel>();
                return _episodes;
            }
            set
            {
                _episodes = value;
            }
        }
    }
}

J3ko/Moviebase/MVC/Models/Detail/GroupDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace J3ko.Moviebase.MVC.Models.Detail
{
    public class GroupDetailModel
    {
        [HiddenInput(DisplayValue = false)]
        public int GroupId { get; set; }

        public string Description { get; set; }

        public int MediaFormatId { get; set; }

        public string Slot { get; set; }

        public string Container { get; set; }

        private List<EpisodeDetailModel> _episodes;

        public List<EpisodeDetailModel> Episodes
        {
            get
            {
                if (_episodes == null)
                    _episodes = new List<EpisodeDetailModel>();
                return _episodes;
            }
            set
            {
                _episodes = value;
            }
        }
    }
}

J3ko/Moviebase/MVC/Models/Detail/TitleDetailEditModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using J3ko.Moviebase.BOL;
using J3ko.Common.Utils;

namespace J3ko.Moviebase.MVC.Models.Detail
{
    //[Cardinality(PropertyName="Groups", MinCount = 1)]
    public class TitleDetailEditModel
    {
        [HiddenInput(DisplayValue = false)]
        public int TitleId { get; set; }

        public bool IsNew 
        {
            get
            {
                return TitleId <= 0;
            }
        }

        [StringLength(255, ErrorMessage = "{0} is too long")]
        [Required(AllowEmptyStrings = false)]
        public string Name { get; set; }

        [StringLength(4000, ErrorMessage = "{0} is too long")]
        [Required(AllowEmptyStrings = false)]
        public string Plot { get; set; }

        public ShortGuid PosterId { get; set; }

        public ShortGuid PosterSmallId { get; set; }

        public string NewPosterUrl { get; set; }

        public string NewSmallPosterUrl { get; set; }

        [StringLength(32, ErrorMessage = "{0} is too long")]
        public string ImdbId { get; set; }

        public IEnumerable<CategoryBO> Categories { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; set; }

        private List<GroupDetailEditModel> _groups;

        public List<GroupDetailEditModel> Groups
        {
            get
            {
                if (_groups == null)
                    _groups = new List<GroupDetailEditModel>();
                return _groups;
            }
            set
            {
                _groups = value;
            }
        }
    }
}

J3ko/Moviebase/MVC/Models/Detail/TitleDetailModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using J3ko.Moviebase.BOL;
using J3ko.Common.Utils;

namespace J3ko.Moviebase.MVC.Models.Detail
{
    public class TitleDetailModel
    {
        [HiddenInput(DisplayValue = false)]
        public int TitleId { get; set; }

        public ShortGuid PosterId { get; set; }

        public string Name { get; set; }

        public string Plot { get; set; }

        public string Category { get; set; }

        [UIHint("ImdbLink")]
        public string ImdbId { get; set; }

        private List<TitleBO> _suggestions;
        [UIHint("SuggestionList")]
        public List<TitleBO> Suggestions
        {
            get
            {
                if (_suggestions == null)
                    _suggestions = new List<TitleBO>();
                return _suggestions;
            }
            set
            {
                _suggestions = value;
            }
        }


        private List<GenreBO> _genres;
        [UIHint("GenreList")]
        public List<GenreBO> Genres
        {
            get
            {
                if (_genres == null)
                    _genres = new List<GenreBO>();
                return _genres;
            }
            set
            {
                _genres = value;
            }
        }

        private List<GroupDetailModel> _groups;
        [UIHint("GroupDetailList")]
        public List<GroupDetailModel> Groups
        {
            get
            {
                if (_groups == null)
                    _groups = new List<GroupDetailModel>();
                return _groups;
            }
            set
            {
                _groups = value;
            }
        }

        private List<TitlePersonBO> _actors;
        [UIHint("ActorList")]
        public List<TitlePersonBO> Actors
        {
            get
            {
                if (_actors == null)
                    _actors = new List<TitlePersonBO>();
                return _actors;
            }
            set
            {
                _actors = value;
            }
        }

        private List<TitlePersonBO> _directors;
        [UIHint("DirectorList")]
        public List<TitlePersonBO> Directors
        {
            get
            {
                if (_directors == null)
                    _directors = new List<TitlePersonBO>();
                return _directors;
            }
            set
            {
                _directors = value;
            }
        }

        private List<TitlePersonBO> _producers;
        [UIHint("ProducerList")]
        public List<TitlePersonBO> Producers
        {
            get
            {
                if (_producers == null)
                    _producers = new List<TitlePersonBO>();
                return _producers;
            }
            set
            {
                _producers = value;
            }
        }
    }
}

J3ko/Moviebase/MVC/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using J3ko.Moviebase.BOL;
using J3ko.Moviebase.BLL;
using J3ko.Moviebase.MVC.Mappers;
using J3ko.Common.Docs;
using System.ComponentModel;
using J3ko.Common.MVC.ModelBinders;
using J3ko.Web.Movies;
using J3ko.Moviebase.MVC.Models.Detail;

namespace J3ko.Moviebase.MVC.Controllers
{
    public class DetailController : BaseController
    {
        private ICatalogService _catserve;
        private ICodeService _codserve;
        private ISuggestionService _sugserve;

        public DetailController()
        {
            _catserve = new CatalogService();
            _codserve = new CodeService();
            _sugserve = SuggestionService.Instance;
        }

        public ActionResult Index(int id)
        {
            TitleBO title = _catserve.GetTitle(id);

            if (title == null || title.Id <= 0)
                throw new HttpException(404, "Title not found");

            DetailMapper map = new DetailMapper(_codserve, _catserve, _sugserve);
            TitleDetailModel model = map.MapTitleDetailModel(title);

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult SyncTitle(int id)
        {
            TitleBO title = null;
            try
            {
                title = _catserve.SyncTitleData(id);
                SetNotification("Title Synced Successfully");
            }
            catch (ApplicationException apex)
            {
                SetNotification(apex.Message);
            }

            return RedirectToAction("Index", id);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Save(int id = 0)
        {
            TitleBO title = _catserve.GetTitle(id) ?? new TitleBO();

            if (title.Id <= 0)
            {
                GroupBO grp = new GroupBO();
                title.Add(grp);
            }

            DetailMapper map = new DetailMapper(_codserve, _catserve, _sugserve);
            TitleDetailEditModel model = map.MapTitleDetailEditModel(title);

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Save(TitleDetailEditModel model)
        {
            DetailMapper map = new DetailMapper(_codserve, _catserve, _sugserve);
            List<MovieBO> movies = MovieInfo;

            try
            {
                if (ModelState.IsValid)
                {
                    TitleBO bo = map.MapTitleBO(model);
                    MovieBO mov = MovieInfo.Find(x => x.ImdbId == bo.ImdbId);

                    if (mov != null)
                        bo = _catserve.SyncTitleData(bo, mov, model.NewPosterUrl, model.NewSmallPosterUrl);
                    else
                        bo = _catserve.SaveTitle(bo, model.NewPosterUrl, model.NewSmallPosterUrl);
 
                    SetNotification("Saved Successfully");
                    return RedirectToAction("Save", new { id = bo.Id });
                }
            }
            catch (ApplicationException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                SetNotification("Save Failed");
            }

            map.PopulateSelectLists(model);
            return View(model);
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult AddEpisode(string containerPrefix)
        {
            ViewData["ContainerPrefix"] = containerPrefix;
            DetailMapper map = new DetailMapper(_codserve, _catserve, _sugserve);
            EpisodeDetailEditModel model = map.MapEpisodeDetailEditModel(new EpisodeBO());
            map.PopulateEpisodeSelectLists(model);

            return PartialView("_EpisodeDetailEditRow", model);
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult AddGroup()
        {
            DetailMapper map = new DetailMapper(_codserve, _catserve, _sugserve);
            GroupBO group = new GroupBO();
            group.Add(new EpisodeBO());
            GroupDetailEditModel model = map.MapGroupDetailEditModel(group);
            map.PopulateGroupSelectLists(model);

            return PartialView("_GroupDetailEditRow", model);
        }

        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        public ActionResult SlotList(int containerId, int include = 0)
        {
            IEnumerable<SlotBO> slots = _codserve.GetAvailableSlots(containerId, include);
            SelectList result = new SelectList(slots, "Label", "Id");

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        [Authorize]
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (_catserve != null)
            {
                _catserve.Dispose();
                _catserve = null;
            }
            if (_codserve != null)
            {
                _codserve.Dispose();
                _codserve = null;
            }
            if (_sugserve != null)
            {
                _sugserve.Dispose();
                _sugserve = null;
            }
            base.Dispose(disposing);
        }
    }
}

J3ko/Moviebase/MVC/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using J3ko.Common.Docs;
using J3ko.Common.Utils;
using J3ko.Moviebase.BLL;
using J3ko.Moviebase.MVC.Mappers;
using J3ko.Web.Movies;
using J3ko.Moviebase.MVC.Models.Shared;
using System.Threading.Tasks;

namespace J3ko.Moviebase.MVC.Controllers
{
    public class SharedController : BaseController
    {
        private ICatalogService _cserve;
        private IImageService _iserve;
        private IMatchService _mserve;

        public SharedController()
            : this(new CatalogService(), new ImageService(), new MatchService())
        { }

        public SharedController(ICatalogService cserve, IImageService iserve, IMatchService mserve)
        {
            _cserve = cserve;
            _iserve = iserve;
            _mserve = mserve;
        }

        [OutputCache(Duration = 3600, VaryByParam = "id")]
        public void PosterAsync(ShortGuid id)
        {
            AsyncManager.OutstandingOperations.Increment();

            Task.Factory.StartNew(() =>
            {
                DocumentBO doc = _iserve.GetImage(id, ImageSize.LargePoster);
                AsyncManager.Parameters["doc"] = doc;
                AsyncManager.OutstandingOperations.Decrement();
            });
        }

        public ActionResult PosterCompleted(DocumentBO doc)
        {
            FileStreamResult result = new FileStreamResult(doc.FileContent, doc.MimeType);
            return result;
        }

        [OutputCache(Duration = 36000, VaryByParam = "id")]
        public void SmallPosterAsync(ShortGuid id)
        {
            AsyncManager.OutstandingOperations.Increment();

            Task.Factory.StartNew(() =>
            {
                DocumentBO doc = _iserve.GetImage(id, ImageSize.SmallPoster);
                AsyncManager.Parameters["doc"] = doc;
                AsyncManager.OutstandingOperations.Decrement();
            });
        }

        public ActionResult SmallPosterCompleted(DocumentBO doc)
        {
            FileStreamResult result = new FileStreamResult(doc.FileContent, doc.MimeType);
            return result;
        }

        [OutputCache(Duration = 36000, VaryByParam = "id")]
        public ActionResult Profile(ShortGuid id)
        {
            DocumentBO doc = _iserve.GetImage(id, ImageSize.Profile);
            FileStreamResult result = new FileStreamResult(doc.FileContent, doc.MimeType);
            return result;
        }


        [ValidateInput(false)]
        public ActionResult GetMatches(string term)
        {
            List<MovieBO> temp = _mserve.Search(term).ToList();

            IEnumerable<MatchModel> result =
                from e in temp
                select new MatchModel
                {
                    ImdbId = e.ImdbId,
                    Plot = e.Plot,
                    Title = e.Title,
                    Posters = GetPosters(e.Posters),
                };

            base.MovieInfo = temp;

            return PartialView("_MatchResultSet", result.ToList());
        }

        private List<MatchPosterModel> GetPosters(IEnumerable<MoviePostersBO> posters)
        {
            return (from p in posters
                    select new MatchPosterModel
                    {
                        PosterUrl = p.PosterUrl,
                        SmallPosterUrl = p.SmallPosterUrl,
                    }).ToList();
        }

        protected override void Dispose(bool disposing)
        {
            if (_iserve != null)
            {
                _iserve.Dispose();
                _iserve = null;
            }
            if (_cserve != null)
            {
                _cserve.Dispose();
                _cserve = null;
            }
            if (_mserve != null)
            {
                _mserve = null;
            }

            base.Dispose(disposing);
        }
    }
}

J3ko/Moviebase/MVC/Views/Detail/EditorTemplates/EpisodeDetailEditModel.cshtml
@model J3ko.Moviebase.MVC.Models.Detail.EpisodeDetailEditModel
@using J3ko.Common.MVC

@{
    ViewBag.Title = "EpisodeDetailEditModel";
}
<div class="episodeRow">
<div class="episodeTop"></div>
<div class="episodeBody">
@using (Html.BeginAjaxContentValidation("form0"))
{
    using (Html.BeginCollectionItem("episodes"))
    {
        <div style="float:left;">
            @Html.LabelFor(x => x.Name)
            <br />
            @Html.TextBoxFor(x => x.Name)
            <br />
            @Html.ValidationMessageFor(x => x.Name)&nbsp;
            <br />
            @Html.LabelFor(x => x.InstanceId)
            <br />
            @Html.DropDownListFor(x => x.InstanceId, new SelectList(Model.Instances, "Id", "Description", Model.InstanceId))
            <br />
            @Html.ValidationMessageFor(x => x.InstanceId)&nbsp;
            <br />
        </div>
        <div style="float:right;margin-right:25px;">
            <a href="#" class="deleteEpisode"><img src="@Url.Content("~/Content/images/del.gif")" alt="Delete Episode" border="0" /></a>
        </div>
        <div class="clear"></div>
    }
}
</div>
<div class="episodeBottom"></div>
</div>

J3ko/Moviebase/MVC/Views/Detail/EditorTemplates/GroupDetailEditModel.cshtml
@model J3ko.Moviebase.MVC.Models.Detail.GroupDetailEditModel
@using J3ko.Common.MVC
@{
    ViewBag.Title = "GroupDetailEditModel";
}
<div class="groupRow">
<div class="boxedTop"></div>
<div class="boxedBody">
@using (Html.BeginAjaxContentValidation("form0"))
{
    using (Html.BeginCollectionItem("groups"))
    {
        <table width="350" style="float:left;">
            <tr>
                <td>
                    @Html.HiddenFor(x => x.GroupId)
                    @Html.LabelFor(x => x.Description)
                    <br />
                    @Html.TextBoxFor(x => x.Description)
                    <br />
                    @Html.ValidationMessageFor(x => x.Description)&nbsp;
                </td>
                <td>
                    @Html.LabelFor(x => x.MediaId)
                    <br />
                    @Html.DropDownListFor(x => x.MediaId, new SelectList(Model.Media, "Id", "Name", Model.MediaId))
                    <br />
                    @Html.ValidationMessageFor(x => x.MediaId)&nbsp;
                </td>
            </tr>
            <tr>
                <td>
                    @Html.LabelFor(x => x.SlotId)
                    <br />
                    @Html.DropDownListFor(x => x.SlotId, new SelectList(Model.Slots, "Id", "Label", Model.SlotId), new { @class = "slotSelector" })
                    <br />
                    @Html.ValidationMessageFor(x => x.SlotId)&nbsp;
                </td>
                <td>
                    @Html.LabelFor(x => x.ContainerId)
                    <br />
                    @Html.DropDownListFor(x => x.ContainerId, new SelectList(Model.Containers, "Id", "Name", Model.ContainerId), new { @class = "containerSelector" })
                    <br />
                    @Html.ValidationMessageFor(x => x.ContainerId)&nbsp;
                </td>
            </tr>
        </table>
        <div style="float:right;margin-right:20px;"><a href="#" class="deleteGroup"><img src="@Url.Content("~/Content/images/del.gif")" alt="Delete Group" border="0" /></a></div>
        <br />
        <div class="clear"></div>
        <br />
        <div class="episodeContainer">
            @Html.EditorFor(x => x.Episodes)
        </div>
        <input type="button" class="addEpisodeDetail" data-href="@Url.Action("AddEpisode", new { containerPrefix = ViewData["ContainerPrefix"] })" value="Add Episode" />
    }
}
</div>
<div class="boxedBottom"></div>
</div>

J3ko/Moviebase/MVC/Views/Detail/EditorTemplates/TitleDetailEditModel.cshtml
@model J3ko.Moviebase.MVC.Models.Detail.TitleDetailEditModel
@{
    ViewBag.Title = "TitleDetailEditModel";
}
<div class="boxedTop titleInfoTop"></div>
<div class="boxedBody titleInfo">
@Html.HiddenFor(x => x.TitleId)
@Html.HiddenFor(x => x.ImdbId, new { @id = "imdbIdInput" })
@Html.HiddenFor(x => x.NewPosterUrl, new { @id = "newPosterUrl" })
@Html.HiddenFor(x => x.NewSmallPosterUrl, new { @id = "newPosterSmallUrl" })
<table width="390">
    <tr>
        <td rowspan="3">
            <div class="posterImageSmallContainer">
                <img src='@Url.Action("SmallPoster", "Shared", new { @id = Model.PosterSmallId.ToString() })' id="posterImage" class="posterImageSmall" alt="@Model.Name" />
            </div>
            @if (!Model.IsNew)
            {
            <div class="editViewEntry">@Html.ActionLink("View", "Index", "Detail", new { @id = Model.TitleId })</div>
            }
        </td>
        <td colspan="2">
            @Html.LabelFor(x => x.Name)
            <br />
            @Html.TextBoxFor(x => x.Name, new { id = "titleNameInput" })
            <br />
            @Html.ValidationMessageFor(x => x.Name)&nbsp;
        </td>
    </tr>
    <tr>
        <td colspan="2">
            @Html.LabelFor(x => x.Plot)
            <br />
            @Html.TextAreaFor(x => x.Plot, new { id = "plotNameInput" })
            <br />
            @Html.ValidationMessageFor(x => x.Plot)&nbsp;
        </td>
    </tr>
    <tr>

        <td>
            @Html.LabelFor(x => x.CategoryId)
            <br />
            @Html.DropDownListFor(x => x.CategoryId, new SelectList(Model.Categories, "Id", "Name", Model.CategoryId))
            <br />
            @Html.ValidationMessageFor(x => x.CategoryId)&nbsp;
        </td>
    </tr>
</table>
</div>
<div class="boxedBottom titleInfoBottom"></div>
<div class="clear"></div>
<br />
<div class="groupContainer">
    @Html.EditorFor(x => x.Groups)
</div>
<input type="button" id="addGroupDetail" data-href="@Url.Action("AddGroup")" value="Add Disc" style="margin-left:15px;" />